name: Run Python script periodically

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'  # Runs every hour (use cron syntax)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python update.py


      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add events.csv
          git commit -m "Update CSV file [skip ci]" || echo "No changes to commit"
          git push
        env:
          # Needed to allow GitHub Actions to push code
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

