name: Run Python script periodically

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (use cron syntax)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python update.py
      - name: Upload events.csv
        uses: actions/upload-artifact@v4
        with:
          name: dataframe-csv
          path: events.csv